## Homework 08: Classification

### Due: Midnight, March 22nd (with usual 2 hour grace period and late policy)

### Overview

In this final homework before starting our course project, we will introduce the essential machine learning paradigm of **classification**. We will work with the **UCI Adult** dataset. This is a binary classification task.

As we’ve discussed in this week’s lessons, the classification workflow is similar to what we’ve done for regression, with a few key differences:
- We use `StratifiedKFold` instead of plain `KFold` so that every fold keeps the original class proportions.
- We use classification metrics (e.g., accuracy, precision, recall, F1-score for binary classification) instead of regression metrics.
- We could explore misclassified instances through a confusion matrix (though we will not do that in this homework).

For this assignment, you’ll build a gradient boosting classification using `HistGradientBoostingClassifier` (HGBC) and explore ways of tuning the hyperparameters, including using the technique of early stopping, which basically avoiding have to tune the number of estimators (called `max_iter` in HGBC). 

HGBC has many advantages, which we explain below. 


### Grading

There are 7 graded problems, each worth 7 points, and you get 1 point free if you complete the assignment.

In [6]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 38.0 MB/s  0:00:006m0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.23 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 36.8 MB/s  0:00:006m0:00:01
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 29.6 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 29.3 MB/s  0:00:00
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 40.9 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install tqdm

Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.67.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (from optuna) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from optuna) (25.0)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.48-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: tqdm in /usr/local/python/3.12.1/lib/python3.12/site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /home/codespace/.local/lib/python3.12/site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /home/codespace/.local/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/codespace/.local/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading sqlalchemy-2.0.48-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 62.0 MB/s  0:00:00
Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.9/613.9 kB 25.9 MB/s  0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [optuna]2m5/6 [optuna]]my]
Successfully installed Mako-1.3.10 alembic-1.18.4 colorlog-6.10.1 greenlet-3.3.2 optuna-4.7.0 sqlalchemy-2.0.48

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [21]:
# General utilities
import os
import io
import time
import zipfile
import requests
from collections import Counter

# Data handling and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from IPython.display import display
 
# Data source
from sklearn.datasets import fetch_openml

 
# scikit-learn core tools 
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    RandomizedSearchCV
)

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

 
# Import model 
from sklearn.ensemble import HistGradientBoostingClassifier
 
# Metrics
from sklearn.metrics import balanced_accuracy_score, classification_report
 
# Distributions for random search
from scipy.stats import loguniform, randint, uniform

# pandas dtypes helpers
from pandas.api.types import is_numeric_dtype, is_categorical_dtype
from pandas import CategoricalDtype

# Optuna Hyperparameter Search tool    (may need to be installed)
import optuna


# Misc

random_seed = 42

def format_hms(seconds):
    return time.strftime("%H:%M:%S", time.gmtime(seconds))

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Prelude 1: Load and Preprocess the UCI Adult Income Dataset

- Load the dataset from sklearn
- Preliminary EDA
- Feature Engineering

In [23]:
# Load and clean
df = fetch_openml(name='adult', version=2, as_frame=True).frame

df.replace("?", np.nan, inplace=True)            # Some datasets use ? instead of Nan for missing data

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       46043 non-null  category
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  category
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  category
 6   occupation      46033 non-null  category
 7   relationship    48842 non-null  category
 8   race            48842 non-null  category
 9   sex             48842 non-null  category
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  47985 non-null  category
 14  class           48842 non-null  category
dtypes: category(9), int64(6)
memory usage: 2.7 MB

#### Check: Is the dataset imbalanced?

In [24]:
print(df['class'].value_counts(normalize=True))

class
<=50K    0.760718
>50K     0.239282
Name: proportion, dtype: float64

**YES:** It looks like this dataset is somewhat imbalanced. Therefore, we will 
1. Tell the model to compensate during training by setting `class_weight='balanced'` when defining the model;
2. Evaluate it `balanced_accuracy` instead of `accuracy` and with class-aware metrics (precision, recall, F1); and
3. [Optional] Adjust the probability threshold instead of relying on raw accuracy alone after examining the precision-recall trade-off you observe at 0.5.

### Feature Engineering

Based on the considerations in **Appendix One**, we'll make the following changes to the dataset to facilitate training:


1. Drop `fnlwgt` and `education`.   
3. Replace `capital-gain` and `capital-loss` by their difference `capital_net` and add a log-scaled version `capital_net_log`.

In [25]:
# Drop the survey-weight column
df_eng = df.drop(columns=["fnlwgt"])

# Keep only the ordinal education feature
df_eng = df_eng.drop(columns=["education"])      # retain 'education-num'

# Combine capital gains and losses, add a log-scaled variant
df_eng["capital_net"]     = df_eng["capital-gain"] - df_eng["capital-loss"]
df_eng["capital_net_log"] = np.log1p(df_eng["capital_net"].clip(lower=0))
df_eng = df_eng.drop(columns=["capital-gain", "capital-loss"])

# check
df_eng.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        46043 non-null  category
 2   education-num    48842 non-null  int64
 3   marital-status   48842 non-null  category
 4   occupation       46033 non-null  category
 5   relationship     48842 non-null  category
 6   race             48842 non-null  category
 7   sex              48842 non-null  category
 8   hours-per-week   48842 non-null  int64
 9   native-country   47985 non-null  category
 10  class            48842 non-null  category
 11  capital_net      48842 non-null  int64
 12  capital_net_log  48842 non-null  float64
dtypes: category(8), float64(1), int64(4)
memory usage: 2.2 MB

#### Separate target and split

Create the feature set `X` and the target set `y` (using `class` as the target) and split the dataset into 80% training and 20% testing sets, making sure to stratify.

In [26]:

X = df_eng.drop(columns=["class"])
y = (df_eng["class"] == ">50K").astype(int)

# Split (with stratification)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=random_seed,
    stratify=y                           # So same proportion of classes in train and test sets
)

print("Train:", X_train.shape, y_train.shape)
print("Test :", X_test.shape,  y_test.shape)

Train: (39073, 12) (39073,)
Test : (9769, 12) (9769,)

### Prelude 2: Create a data pipeline and the `HistGradientBoostingClassifier` model

Histogram-based gradient boosting improves on the standard version by:

* **Histogram splits:** bins each feature into ≤ `max_bins` quantiles (i.e., each bin is approximately the same size) and tests splits only between bins, slashing compute time and scaling to large data sets. Default for `max_bins` = 255. 
* **Native NaN handling:** treats missing values as their own bin—no imputation needed.
* **Native Categorical Support**: accepts integer-encoded categories directly and tests “category c vs. all others” splits, eliminating one-hot blow-ups and fake orderings.
* **Built-in early stopping:** stops training after no improvement in validation loss after `n_iter_no_change` rounds. `tol` defines "improvement" (default is 1e-7). 
* **Leaf shrinkage:** adds `l2_regularization`, which ridge-shrinks each leaf value (without changing tree shape) so tiny, noisy leaves have less effect.

>**Summary:**  Histogram-based GB trades a tiny approximation error (binning) for a **huge speed-up** and adds extra conveniences, making it the preferred choice for large tabular data sets. Tuning workflow relies on **Early stopping** to stop training before overfitting occurs.

In [27]:
# Define a baseline model 

HGBC_model = HistGradientBoostingClassifier(
    # tree structure and learning rate
    learning_rate=0.1,            # These 5 parameters are at defaults for our baseline training in Problem 1             
    max_leaf_nodes=31,            # but will be tuned by randomized search in Problem 2 and Optuna in Problem 3               
    max_depth=None,               
    min_samples_leaf=20,          
    l2_regularization=0.0,        

    # bins and iteration
    max_bins=255,                 # default
    max_iter=500,                 # high enough for early stopping
    early_stopping=True,
    n_iter_no_change=20,
    validation_fraction=0.2,      # 20% monitored for early stopping
    tol=1e-7,                     # default tolerance for validation improvement

    # class imbalance
    class_weight="balanced",

    random_state=random_seed,
    verbose=0
)

### Create a pipeline appropriate for HGBC 

**Why use a `Pipeline` instead of encoding in the dataset first?**

* **Avoid data leakage.** In each CV fold, the `OrdinalEncoder` is refit only on that fold’s training data, so the validation split never influences the encoder.
* **Single, reusable object.** The pipeline bundles preprocessing + model, letting you call `fit`/`predict` on raw data anywhere (CV, Optuna, production) with identical behavior.
* **Compatible with search tools.** `cross_validate`, `GridSearchCV`, and Optuna expect an estimator that can be cloned and refit; a pipeline meets that requirement automatically.

Put simply, the pipeline gives you leak-free evaluation and portable, hassle-free tuning without extra code.

In [28]:
enc = OrdinalEncoder(
    handle_unknown="use_encoded_value",   # Allow unseen categories during transform
    unknown_value=-1,                     # Code for unseen categories
    encoded_missing_value=-2,             # Code for missing values (NaN)
    dtype=np.int64                        # Needed for HistGradientBoostingClassifier
)

# Categorical features
cat_cols = X.select_dtypes(exclude=["number"]).columns.tolist()

# Numeric features (everything that isn’t object / category)
num_cols = X.select_dtypes(include=["number"]).columns.tolist()

preprocess = ColumnTransformer(
    [("cat", enc, cat_cols),
     ("num", "passthrough", num_cols)]
)

pipelined_model = Pipeline([
    ("prep", preprocess),
    ("gb",   HGBC_model)
])

## Problem 1: Baseline Cross-Validation with F1

In this problem, you will run a baseline cross-validation evaluation of your `HistGradientBoostingClassifier` pipeline, using `HGBC_model` defined above. 

**Background:**

* Since the Adult dataset is imbalanced (about 24% positives, 76% negatives), accuracy alone is not reliable.
* We will use the **F1 score** as the evaluation metric, since it balances precision (avoiding false positives) and recall (avoiding false negatives) in a single measure. This is a fairer metric for imbalanced classification, where both types of error matter.
* We will apply **5-fold stratified cross-validation** to make sure each fold has the same proportion of the classes as the original dataset.
* Repeated cross-validation is optional and not required here, because the Adult dataset is large and `HistGradientBoostingClassifier` is robust to small sampling differences. 

**Instructions:**

1. Set up a `StratifiedKFold` cross-validation object with 5 splits, shuffling enabled, and `random_state=random_seed`.
2. Use `cross_val_score` to estimate the mean F1 score and its standard deviation across the folds.
3. Print out the mean and standard deviation of the F1 score, rounded to 4 decimal places.
4. Answer the graded question.

In [29]:
# Your code here
from sklearn.model_selection import StratifiedKFold, cross_val_score

# 1. Define stratified 5-fold CV
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=random_seed
)

# 2. Run cross-validation using F1 score
scores = cross_val_score(
    pipelined_model,
    X_train,
    y_train,
    cv=cv,
    scoring="f1",
    n_jobs=-1
)

print("F1 scores:", scores)
print(f"Mean F1: {scores.mean():.4f}")
print(f"Std  F1: {scores.std():.4f}")

F1 scores: [0.71761542 0.71247818 0.71314031 0.7119448  0.7065073 ]
Mean F1: 0.7123
Std  F1: 0.0035

### Problem 1 Graded Answer

Set `a1` to the mean F1 score of the baseline model.

In [30]:
 # Your answer here

a1 = scores.mean()                   # replace 0 with an expression

In [31]:
# DO NOT change this cell in any way

print(f'a1 = {a1:.4f}')

a1 = 0.7123

## Problem 2: Hyperparameter Optimization with Randomized Search for F1

In this problem, you will tune your `pipelined_model` using `RandomizedSearchCV` to identify the best combination of tree structure and learning rate parameters that maximize the **F1 score**.

**Background:**
The F1 score is our main metric because it balances precision and recall on an imbalanced dataset. Optimizing hyperparameters for F1 ensures we manage both false positives and false negatives in a single measure.

**Instructions:**

1. Set up a randomized search over the following hyperparameter ranges, using appropriate random-number distributions:

   * `learning_rate` (log-uniform between 1e-3 and 0.3)
   * `max_leaf_nodes` (integer from 16 to 256)
   * `max_depth` (integer from 2 to 10)
   * `min_samples_leaf` (integer from 10 to 200)
   * `l2_regularization` (uniform between 0.0 and 2.0)
2. Use **5-fold stratified cross-validation**, with the same settings as in Problem 1.
3. Start `n_iter` at 10 or 20 to prototype, but try for 50 - 100 trials. More trials will generally yield better results, if your time and machine allow.
4. After running the search, show a neatly formatted table of the top 5 results, using `display(...)` showing their mean F1 scores, standard deviation, and the chosen hyperparameter values.
5. Answer the graded question.

In [32]:
# Your code here

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from scipy.stats import loguniform, randint, uniform

# 1. Define parameter distributions
param_dist = {
    "gb__learning_rate": loguniform(1e-3, 3e-1),
    "gb__max_leaf_nodes": randint(16, 257),
    "gb__max_depth": randint(2, 11),
    "gb__min_samples_leaf": randint(10, 201),
    "gb__l2_regularization": uniform(0.0, 2.0)
}

# 2. Stratified 5-fold CV
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=random_seed
)

# 3. Randomized search
search = RandomizedSearchCV(
    estimator=pipelined_model,
    param_distributions=param_dist,
    n_iter=50,                     # increase to 100 if time allows
    scoring="f1",
    cv=cv,
    n_jobs=-1,
    verbose=1,
    random_state=random_seed,
    return_train_score=False
)

# 4. Run the search
search.fit(X_train, y_train)

# 5. Display top 5 results
results = pd.DataFrame(search.cv_results_)
cols = [
    "mean_test_score", "std_test_score",
    "param_gb__learning_rate",
    "param_gb__max_leaf_nodes",
    "param_gb__max_depth",
    "param_gb__min_samples_leaf",
    "param_gb__l2_regularization"
]

display(results[cols].sort_values("mean_test_score", ascending=False).head(5))

print("Best F1:", search.best_score_)
print("Best params:", search.best_params_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

,mean_test_score,std_test_score,param_gb__learning_rate,param_gb__max_leaf_nodes,param_gb__max_depth,param_gb__min_samples_leaf,param_gb__l2_regularization
19,0.712000,0.003063,0.127541,48,3,57,1.829919
21,0.711405,0.003213,0.157664,242,2,110,1.275115
14,0.711026,0.002790,0.070991,39,6,163,1.689068
2,0.710635,0.002146,0.040957,17,6,97,0.285734
0,0.710227,0.003785,0.226482,204,9,30,0.749080

Best F1: 0.7119997861837095
Best params: {'gb__l2_regularization': np.float64(1.8299193510875615), 'gb__learning_rate': np.float64(0.12754065069696732), 'gb__max_depth': 3, 'gb__max_leaf_nodes': 48, 'gb__min_samples_leaf': 57}

### Problem 2 Graded Answer

Set `a2` to the mean F1 score of the best model found.

In [33]:
 # Your answer here

a2 = search.best_score_                     # replace 0 with your answer, may copy from the displayed results

In [34]:
# DO NOT change this cell in any way

print(f'a2 = {a2:.4f}')

a2 = 0.7120

## Problem 3: Hyperparameter Optimization with Optuna for F1

In this problem, you will explore **Optuna**, a powerful hyperparameter optimization framework, to identify the best combination of hyperparameters that maximize the F1 score of your `pipelined_model`.

**Background:**
Optuna uses a smarter sampling strategy than grid search or randomized search, allowing you to explore the hyperparameter space more efficiently. It also supports *pruning*, which can stop unpromising trials early to save time. This makes it a popular SOTA optimization tool.

**Before you start** browse the [Optuna documentation](https://optuna.org) and view the [tutorial video](https://optuna.readthedocs.io/en/stable/tutorial/index.html). 

As before, we focus on the **F1 score** because it balances precision and recall, making it more robust on an imbalanced dataset.

**Instructions:**

1. Define an Optuna objective function to optimize F1 score, sampling the exact same hyperparameter ranges you did in Problem 2 and using the same CV settings.  
3. Set up an Optuna study with a reasonable number of trials (e.g., up to 100 depending on runtime resources--on my machine Optuna runs about 10x faster than randomized search for the same number of trials, but YMMV).
4. After running the optimization, `display` a clean table with the top 5 trials showing their F1 scores and corresponding hyperparameter settings.
5. Answer the graded question. 

**Note:**  There are many resources on Optuna you can find on the web, but for this problem, you have my permission to let ChatGPT write the code for you.

In [35]:
# Your code here

import optuna
from sklearn.model_selection import StratifiedKFold, cross_val_score

# 1. Define the objective function
def objective(trial):

    # Sample hyperparameters (same ranges as Problem 2)
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 3e-1, log=True),
        "max_leaf_nodes": trial.suggest_int("max_leaf_nodes", 16, 256),
        "max_depth": trial.suggest_int("max_depth", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 10, 200),
        "l2_regularization": trial.suggest_float("l2_regularization", 0.0, 2.0)
    }

    # Clone the pipeline and update HGBC params
    model = Pipeline([
        ("prep", preprocess),
        ("gb", HistGradientBoostingClassifier(
            max_bins=255,
            max_iter=500,
            early_stopping=True,
            n_iter_no_change=20,
            validation_fraction=0.2,
            class_weight="balanced",
            random_state=random_seed,
            **params
        ))
    ])

    # 5-fold stratified CV
    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=random_seed
    )

    # Evaluate F1
    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="f1",
        n_jobs=-1
    )

    return scores.mean()


# 2. Create and run the study
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50, show_progress_bar=True)

# 3. Show top 5 trials
top_trials = sorted(study.trials, key=lambda t: t.value, reverse=True)[:5]

rows = []
for t in top_trials:
    row = {"F1": t.value}
    row.update(t.params)
    rows.append(row)

display(pd.DataFrame(rows))

print("Best F1:", study.best_value)
print("Best params:", study.best_params)

[I 2026-03-15 16:28:43,001] A new study created in memory with name: no-name-1c1629da-884c-4e75-977f-e1cb4055ac7c
Best trial: 0. Best value: 0.685376:   2%|▏         | 1/50 [00:16<13:39, 16.73s/it]

[I 2026-03-15 16:28:59,736] Trial 0 finished with value: 0.6853761023520551 and parameters: {'learning_rate': 0.004436112328702301, 'max_leaf_nodes': 219, 'max_depth': 7, 'min_samples_leaf': 17, 'l2_regularization': 1.5212419814382647}. Best is trial 0 with value: 0.6853761023520551.

Best trial: 0. Best value: 0.685376:   4%|▍         | 2/50 [00:29<11:26, 14.30s/it]

[I 2026-03-15 16:29:12,332] Trial 1 finished with value: 0.6744695743459952 and parameters: {'learning_rate': 0.0037608600096032305, 'max_leaf_nodes': 101, 'max_depth': 6, 'min_samples_leaf': 51, 'l2_regularization': 0.27294293624164934}. Best is trial 0 with value: 0.6853761023520551.

Best trial: 2. Best value: 0.710002:   6%|▌         | 3/50 [00:34<07:58, 10.19s/it]

[I 2026-03-15 16:29:17,632] Trial 2 finished with value: 0.7100024998333778 and parameters: {'learning_rate': 0.08453992797024228, 'max_leaf_nodes': 122, 'max_depth': 8, 'min_samples_leaf': 174, 'l2_regularization': 0.22551107995108954}. Best is trial 2 with value: 0.7100024998333778.

Best trial: 3. Best value: 0.711611:   8%|▊         | 4/50 [00:39<06:06,  7.96s/it]

[I 2026-03-15 16:29:22,178] Trial 3 finished with value: 0.7116110128842237 and parameters: {'learning_rate': 0.17389385421859946, 'max_leaf_nodes': 190, 'max_depth': 7, 'min_samples_leaf': 171, 'l2_regularization': 0.7425462365295614}. Best is trial 3 with value: 0.7116110128842237.

Best trial: 3. Best value: 0.711611:  10%|█         | 5/50 [00:50<06:46,  9.03s/it]

[I 2026-03-15 16:29:33,105] Trial 4 finished with value: 0.6671845452317224 and parameters: {'learning_rate': 0.003242967049920881, 'max_leaf_nodes': 207, 'max_depth': 5, 'min_samples_leaf': 92, 'l2_regularization': 0.1924154465806387}. Best is trial 3 with value: 0.7116110128842237.

Best trial: 3. Best value: 0.711611:  12%|█▏        | 6/50 [00:56<05:51,  7.99s/it]

[I 2026-03-15 16:29:39,058] Trial 5 finished with value: 0.6209883108168207 and parameters: {'learning_rate': 0.0029214183729279457, 'max_leaf_nodes': 164, 'max_depth': 2, 'min_samples_leaf': 177, 'l2_regularization': 0.01897254315579744}. Best is trial 3 with value: 0.7116110128842237.

Best trial: 3. Best value: 0.711611:  14%|█▍        | 7/50 [01:04<05:50,  8.15s/it]

[I 2026-03-15 16:29:47,544] Trial 6 finished with value: 0.7102370993997671 and parameters: {'learning_rate': 0.08039473575317878, 'max_leaf_nodes': 112, 'max_depth': 4, 'min_samples_leaf': 145, 'l2_regularization': 0.217317766651}. Best is trial 3 with value: 0.7116110128842237.

Best trial: 7. Best value: 0.712506:  16%|█▌        | 8/50 [01:17<06:47,  9.70s/it]

[I 2026-03-15 16:30:00,573] Trial 7 finished with value: 0.7125063309087306 and parameters: {'learning_rate': 0.0224365599601095, 'max_leaf_nodes': 160, 'max_depth': 7, 'min_samples_leaf': 19, 'l2_regularization': 0.05806709344078653}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  18%|█▊        | 9/50 [01:24<06:02,  8.83s/it]

[I 2026-03-15 16:30:07,489] Trial 8 finished with value: 0.6763057515591813 and parameters: {'learning_rate': 0.008650221358065008, 'max_leaf_nodes': 100, 'max_depth': 3, 'min_samples_leaf': 78, 'l2_regularization': 0.6226750311823217}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  20%|██        | 10/50 [01:31<05:29,  8.24s/it]

[I 2026-03-15 16:30:14,405] Trial 9 finished with value: 0.6318882107452761 and parameters: {'learning_rate': 0.002352128359425982, 'max_leaf_nodes': 141, 'max_depth': 3, 'min_samples_leaf': 104, 'l2_regularization': 0.3957159194345734}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  22%|██▏       | 11/50 [01:41<05:41,  8.77s/it]

[I 2026-03-15 16:30:24,363] Trial 10 finished with value: 0.710868230381026 and parameters: {'learning_rate': 0.024132010171983444, 'max_leaf_nodes': 39, 'max_depth': 10, 'min_samples_leaf': 10, 'l2_regularization': 1.2891370324054272}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  24%|██▍       | 12/50 [01:44<04:27,  7.03s/it]

[I 2026-03-15 16:30:27,431] Trial 11 finished with value: 0.7099988496458433 and parameters: {'learning_rate': 0.1529063515754929, 'max_leaf_nodes': 251, 'max_depth': 9, 'min_samples_leaf': 140, 'l2_regularization': 0.8278087193438395}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  26%|██▌       | 13/50 [01:54<04:51,  7.88s/it]

[I 2026-03-15 16:30:37,247] Trial 12 finished with value: 0.7066753637505196 and parameters: {'learning_rate': 0.027809686066999306, 'max_leaf_nodes': 186, 'max_depth': 7, 'min_samples_leaf': 197, 'l2_regularization': 1.013597653742547}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  28%|██▊       | 14/50 [01:56<03:44,  6.25s/it]

[I 2026-03-15 16:30:39,738] Trial 13 finished with value: 0.7093633360518238 and parameters: {'learning_rate': 0.2649807534731264, 'max_leaf_nodes': 165, 'max_depth': 6, 'min_samples_leaf': 133, 'l2_regularization': 0.6491153972001359}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  30%|███       | 15/50 [02:04<03:58,  6.81s/it]

[I 2026-03-15 16:30:47,848] Trial 14 finished with value: 0.7101866199857501 and parameters: {'learning_rate': 0.049742978011866244, 'max_leaf_nodes': 64, 'max_depth': 8, 'min_samples_leaf': 53, 'l2_regularization': 1.8663200821371024}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  32%|███▏      | 16/50 [02:15<04:35,  8.10s/it]

[I 2026-03-15 16:30:58,962] Trial 15 finished with value: 0.7042562297880017 and parameters: {'learning_rate': 0.01398674491840691, 'max_leaf_nodes': 250, 'max_depth': 6, 'min_samples_leaf': 50, 'l2_regularization': 1.1437617908194098}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  34%|███▍      | 17/50 [02:31<05:40, 10.32s/it]

[I 2026-03-15 16:31:14,419] Trial 16 finished with value: 0.6706163790829568 and parameters: {'learning_rate': 0.001054276095104281, 'max_leaf_nodes': 207, 'max_depth': 8, 'min_samples_leaf': 116, 'l2_regularization': 0.560227855334201}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  36%|███▌      | 18/50 [02:33<04:11,  7.85s/it]

[I 2026-03-15 16:31:16,529] Trial 17 finished with value: 0.708530171468196 and parameters: {'learning_rate': 0.2658037744793461, 'max_leaf_nodes': 151, 'max_depth': 10, 'min_samples_leaf': 162, 'l2_regularization': 1.480365982362832}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  38%|███▊      | 19/50 [02:42<04:17,  8.31s/it]

[I 2026-03-15 16:31:25,918] Trial 18 finished with value: 0.6874669777397424 and parameters: {'learning_rate': 0.009499545135605449, 'max_leaf_nodes': 174, 'max_depth': 5, 'min_samples_leaf': 77, 'l2_regularization': 0.8125978179509697}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  40%|████      | 20/50 [02:48<03:44,  7.48s/it]

[I 2026-03-15 16:31:31,470] Trial 19 finished with value: 0.7101934778589738 and parameters: {'learning_rate': 0.05027673288699445, 'max_leaf_nodes': 228, 'max_depth': 7, 'min_samples_leaf': 30, 'l2_regularization': 0.041519393725786946}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  42%|████▏     | 21/50 [02:52<03:05,  6.40s/it]

[I 2026-03-15 16:31:35,338] Trial 20 finished with value: 0.7111273121780921 and parameters: {'learning_rate': 0.12725565818645274, 'max_leaf_nodes': 191, 'max_depth': 9, 'min_samples_leaf': 195, 'l2_regularization': 1.9104123027256819}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  44%|████▍     | 22/50 [02:56<02:39,  5.69s/it]

[I 2026-03-15 16:31:39,370] Trial 21 finished with value: 0.7104950235396862 and parameters: {'learning_rate': 0.12223152382184796, 'max_leaf_nodes': 185, 'max_depth': 9, 'min_samples_leaf': 195, 'l2_regularization': 1.9520562298902184}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  46%|████▌     | 23/50 [02:59<02:10,  4.82s/it]

[I 2026-03-15 16:31:42,135] Trial 22 finished with value: 0.7105186392073326 and parameters: {'learning_rate': 0.18563101613590421, 'max_leaf_nodes': 197, 'max_depth': 9, 'min_samples_leaf': 158, 'l2_regularization': 1.6737893254744403}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  48%|████▊     | 24/50 [03:08<02:41,  6.23s/it]

[I 2026-03-15 16:31:51,682] Trial 23 finished with value: 0.7107278348517023 and parameters: {'learning_rate': 0.051102785260294985, 'max_leaf_nodes': 159, 'max_depth': 8, 'min_samples_leaf': 182, 'l2_regularization': 1.2324843703480126}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  50%|█████     | 25/50 [03:14<02:32,  6.09s/it]

[I 2026-03-15 16:31:57,445] Trial 24 finished with value: 0.7099549652419143 and parameters: {'learning_rate': 0.08777985544535644, 'max_leaf_nodes': 130, 'max_depth': 7, 'min_samples_leaf': 119, 'l2_regularization': 0.8793208572350645}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  52%|█████▏    | 26/50 [03:24<02:58,  7.42s/it]

[I 2026-03-15 16:32:07,969] Trial 25 finished with value: 0.710202507642502 and parameters: {'learning_rate': 0.03238274577452044, 'max_leaf_nodes': 232, 'max_depth': 9, 'min_samples_leaf': 156, 'l2_regularization': 0.5009292769930305}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  54%|█████▍    | 27/50 [03:31<02:41,  7.03s/it]

[I 2026-03-15 16:32:14,089] Trial 26 finished with value: 0.7110645106655706 and parameters: {'learning_rate': 0.11907453224060799, 'max_leaf_nodes': 77, 'max_depth': 5, 'min_samples_leaf': 190, 'l2_regularization': 1.7340944234233266}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  56%|█████▌    | 28/50 [03:44<03:19,  9.06s/it]

[I 2026-03-15 16:32:27,890] Trial 27 finished with value: 0.706944981158433 and parameters: {'learning_rate': 0.017305729849306235, 'max_leaf_nodes': 183, 'max_depth': 10, 'min_samples_leaf': 127, 'l2_regularization': 0.9925239256339042}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  58%|█████▊    | 29/50 [03:48<02:34,  7.34s/it]

[I 2026-03-15 16:32:31,202] Trial 28 finished with value: 0.7118538038844532 and parameters: {'learning_rate': 0.18936678624616488, 'max_leaf_nodes': 143, 'max_depth': 6, 'min_samples_leaf': 169, 'l2_regularization': 0.38718716768978223}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  60%|██████    | 30/50 [03:50<01:56,  5.82s/it]

[I 2026-03-15 16:32:33,494] Trial 29 finished with value: 0.7098704950278171 and parameters: {'learning_rate': 0.19911214807297864, 'max_leaf_nodes': 143, 'max_depth': 6, 'min_samples_leaf': 26, 'l2_regularization': 0.3752175932604882}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  62%|██████▏   | 31/50 [03:52<01:28,  4.68s/it]

[I 2026-03-15 16:32:35,518] Trial 30 finished with value: 0.7097432819983026 and parameters: {'learning_rate': 0.29050854653088753, 'max_leaf_nodes': 19, 'max_depth': 7, 'min_samples_leaf': 166, 'l2_regularization': 0.3995659525649904}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  64%|██████▍   | 32/50 [03:56<01:22,  4.56s/it]

[I 2026-03-15 16:32:39,802] Trial 31 finished with value: 0.7096241480651174 and parameters: {'learning_rate': 0.13122172253654585, 'max_leaf_nodes': 215, 'max_depth': 7, 'min_samples_leaf': 148, 'l2_regularization': 0.130019958345266}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  66%|██████▌   | 33/50 [04:04<01:34,  5.57s/it]

[I 2026-03-15 16:32:47,714] Trial 32 finished with value: 0.7101464453578525 and parameters: {'learning_rate': 0.06456210654531344, 'max_leaf_nodes': 196, 'max_depth': 6, 'min_samples_leaf': 184, 'l2_regularization': 0.7358344125106518}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  68%|██████▊   | 34/50 [04:18<02:10,  8.16s/it]

[I 2026-03-15 16:33:01,923] Trial 33 finished with value: 0.6825479378937749 and parameters: {'learning_rate': 0.006415866310401625, 'max_leaf_nodes': 123, 'max_depth': 8, 'min_samples_leaf': 171, 'l2_regularization': 0.3190284587677713}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  70%|███████   | 35/50 [04:22<01:40,  6.68s/it]

[I 2026-03-15 16:33:05,146] Trial 34 finished with value: 0.7097443052188148 and parameters: {'learning_rate': 0.19467742849396127, 'max_leaf_nodes': 172, 'max_depth': 5, 'min_samples_leaf': 200, 'l2_regularization': 0.47683678924874606}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  72%|███████▏  | 36/50 [04:28<01:33,  6.71s/it]

[I 2026-03-15 16:33:11,933] Trial 35 finished with value: 0.711383265772214 and parameters: {'learning_rate': 0.09380942990711819, 'max_leaf_nodes': 154, 'max_depth': 4, 'min_samples_leaf': 176, 'l2_regularization': 1.464540784380215}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  74%|███████▍  | 37/50 [04:35<01:27,  6.75s/it]

[I 2026-03-15 16:33:18,770] Trial 36 finished with value: 0.7107963460779312 and parameters: {'learning_rate': 0.08237764187047701, 'max_leaf_nodes': 107, 'max_depth': 4, 'min_samples_leaf': 174, 'l2_regularization': 0.12058514479501886}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  76%|███████▌  | 38/50 [04:43<01:24,  7.00s/it]

[I 2026-03-15 16:33:26,361] Trial 37 finished with value: 0.7074512435170793 and parameters: {'learning_rate': 0.03856910186312633, 'max_leaf_nodes': 155, 'max_depth': 4, 'min_samples_leaf': 94, 'l2_regularization': 1.4447575886024708}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  78%|███████▊  | 39/50 [04:49<01:13,  6.71s/it]

[I 2026-03-15 16:33:32,376] Trial 38 finished with value: 0.7091712294793089 and parameters: {'learning_rate': 0.09810286062262624, 'max_leaf_nodes': 86, 'max_depth': 2, 'min_samples_leaf': 67, 'l2_regularization': 0.21643044638209719}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  80%|████████  | 40/50 [04:53<00:59,  6.00s/it]

[I 2026-03-15 16:33:36,714] Trial 39 finished with value: 0.7109113131495386 and parameters: {'learning_rate': 0.19201834020292097, 'max_leaf_nodes': 144, 'max_depth': 3, 'min_samples_leaf': 150, 'l2_regularization': 1.0147445965791864}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  82%|████████▏ | 41/50 [05:01<00:59,  6.56s/it]

[I 2026-03-15 16:33:44,590] Trial 40 finished with value: 0.7120588813739348 and parameters: {'learning_rate': 0.06467560047366482, 'max_leaf_nodes': 123, 'max_depth': 5, 'min_samples_leaf': 177, 'l2_regularization': 1.3781457153556624}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  84%|████████▍ | 42/50 [05:09<00:55,  6.91s/it]

[I 2026-03-15 16:33:52,316] Trial 41 finished with value: 0.7112244047327472 and parameters: {'learning_rate': 0.06734189341731806, 'max_leaf_nodes': 117, 'max_depth': 5, 'min_samples_leaf': 184, 'l2_regularization': 1.6000053459220935}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  86%|████████▌ | 43/50 [05:17<00:50,  7.15s/it]

[I 2026-03-15 16:34:00,023] Trial 42 finished with value: 0.6978603427268192 and parameters: {'learning_rate': 0.021405468717953888, 'max_leaf_nodes': 132, 'max_depth': 4, 'min_samples_leaf': 172, 'l2_regularization': 1.424179019605098}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  88%|████████▊ | 44/50 [05:26<00:46,  7.72s/it]

[I 2026-03-15 16:34:09,067] Trial 43 finished with value: 0.708560969585746 and parameters: {'learning_rate': 0.03609201521750714, 'max_leaf_nodes': 98, 'max_depth': 6, 'min_samples_leaf': 164, 'l2_regularization': 1.3777266580041014}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  90%|█████████ | 45/50 [05:33<00:37,  7.58s/it]

[I 2026-03-15 16:34:16,311] Trial 44 finished with value: 0.7101145949274473 and parameters: {'learning_rate': 0.06480946900677294, 'max_leaf_nodes': 171, 'max_depth': 4, 'min_samples_leaf': 138, 'l2_regularization': 1.167383467031218}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  92%|█████████▏| 46/50 [05:37<00:26,  6.53s/it]

[I 2026-03-15 16:34:20,398] Trial 45 finished with value: 0.7109773036761722 and parameters: {'learning_rate': 0.1546006237663159, 'max_leaf_nodes': 135, 'max_depth': 5, 'min_samples_leaf': 153, 'l2_regularization': 1.3527370137096653}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  94%|█████████▍| 47/50 [05:43<00:18,  6.29s/it]

[I 2026-03-15 16:34:26,140] Trial 46 finished with value: 0.7101435161205851 and parameters: {'learning_rate': 0.09601427145102233, 'max_leaf_nodes': 148, 'max_depth': 7, 'min_samples_leaf': 181, 'l2_regularization': 1.5757269915345333}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  96%|█████████▌| 48/50 [05:45<00:10,  5.15s/it]

[I 2026-03-15 16:34:28,612] Trial 47 finished with value: 0.7101384985226087 and parameters: {'learning_rate': 0.23159214548200371, 'max_leaf_nodes': 121, 'max_depth': 6, 'min_samples_leaf': 99, 'l2_regularization': 0.6290245566787186}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506:  98%|█████████▊| 49/50 [05:53<00:05,  5.88s/it]

[I 2026-03-15 16:34:36,219] Trial 48 finished with value: 0.6615121128377587 and parameters: {'learning_rate': 0.004540535297961461, 'max_leaf_nodes': 162, 'max_depth': 3, 'min_samples_leaf': 113, 'l2_regularization': 1.7947409587620489}. Best is trial 7 with value: 0.7125063309087306.

Best trial: 7. Best value: 0.712506: 100%|██████████| 50/50 [05:56<00:00,  7.13s/it]

[I 2026-03-15 16:34:39,372] Trial 49 finished with value: 0.7092342807914741 and parameters: {'learning_rate': 0.15367304996228567, 'max_leaf_nodes': 176, 'max_depth': 6, 'min_samples_leaf': 142, 'l2_regularization': 0.26948750748832706}. Best is trial 7 with value: 0.7125063309087306.

,F1,learning_rate,max_leaf_nodes,max_depth,min_samples_leaf,l2_regularization
0,0.712506,0.022437,160,7,19,0.058067
1,0.712059,0.064676,123,5,177,1.378146
2,0.711854,0.189367,143,6,169,0.387187
3,0.711611,0.173894,190,7,171,0.742546
4,0.711383,0.093809,154,4,176,1.464541

Best F1: 0.7125063309087306
Best params: {'learning_rate': 0.0224365599601095, 'max_leaf_nodes': 160, 'max_depth': 7, 'min_samples_leaf': 19, 'l2_regularization': 0.05806709344078653}

### Problem 3 Graded Answer

Set `a3` to the mean F1 score of the best model found.

In [36]:
 # Your answer here

a3 = study.best_value                    # replace 0 with your answer, may copy from the displayed results

In [37]:
# DO NOT change this cell in any way

print(f'a3 = {a3:.4f}')

a3 = 0.7125

## Problem 4: Final Model Evaluation on Test Set

In this problem, you will take the best hyperparameter configuration you found in your earlier experiments (Randomized Search or Optuna) and fully evaluate the resulting model on the test set.

**Background:**
When performing hyperparameter tuning, we typically optimize for a single metric (e.g., F1). However, before deployment, it is essential to check **all relevant metrics** on the final test set to understand the model’s behavior in a balanced way.

**Instructions:**

1. Take the best hyperparameters you found in Problems 2 or 3 and apply them to your `pipelined_model`.
2. Re-train this final tuned model on the **entire training set** (not just the folds).
3. Evaluate the final model on the heldout **test set**, reporting the following metrics:

   * Precision
   * Recall
   * F1 score
   * Balanced accuracy
4. Use `classification_report` **on the test set** to print precision, recall, and F1 score, and use `balanced_accuracy_score` separately to calculate and print balanced accuracy.
5. Answer the graded questions.

**Note:** We evaluate the metrics on the test set because it was never seen during training or hyperparameter tuning. This gives us an unbiased estimate of how the model will perform on truly unseen data. Evaluating on the training set would be misleading, because the model has already learned from that data and could appear artificially good.

In [38]:
# Your code here

best_params = study.best_params   # or search.best_params_ if using RandomizedSearchCV

final_model = Pipeline([
    ("prep", preprocess),
    ("gb", HistGradientBoostingClassifier(
        max_bins=255,
        max_iter=500,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.2,
        class_weight="balanced",
        random_state=random_seed,
        **best_params
    ))
])

In [39]:
final_model.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('cat',
                                                  OrdinalEncoder(dtype=<class 'numpy.int64'>,
                                                                 encoded_missing_value=-2,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['workclass',
                                                   'marital-status',
                                                   'occupation', 'relationship',
                                                   'race', 'sex',
                                                   'native-country']),
                                                 ('num', 'passthrough',
                                                  ['age', 'education-num',
                                                   'hours-per-week',
                                                   'capital_net',
                                                   'capital_net_log'])])),
                ('gb',
                 HistGradientBoostingClassifier(class_weight='balanced',
                                                early_stopping=True,
                                                l2_regularization=0.05806709344078653,
                                                learning_rate=0.0224365599601095,
                                                max_depth=7, max_iter=500,
                                                max_leaf_nodes=160,
                                                min_samples_leaf=19,
                                                n_iter_no_change=20,
                                                random_state=42,
                                                validation_fraction=0.2))])

In [40]:
y_pred = final_model.predict(X_test)

In [41]:
from sklearn.metrics import classification_report, balanced_accuracy_score

# Balanced accuracy
bal_acc = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy:", bal_acc)

# Full classification report
report = classification_report(y_test, y_pred, output_dict=True)
print(classification_report(y_test, y_pred))

# Extract macro precision and recall
macro_precision = report["macro avg"]["precision"]
macro_recall    = report["macro avg"]["recall"]

print("Macro Precision:", macro_precision)
print("Macro Recall:", macro_recall)

Balanced Accuracy: 0.8428996151534522
              precision    recall  f1-score   support

           0       0.95      0.82      0.88      7431
           1       0.60      0.87      0.71      2338

    accuracy                           0.83      9769
   macro avg       0.78      0.84      0.80      9769
weighted avg       0.87      0.83      0.84      9769

Macro Precision: 0.7764536791177135
Macro Recall: 0.8428996151534522

### Problem 4 Graded Questions

- Set `a4a` to the balanced accuracy score of the best model.
- Set `a4b` to the macro average precision of this model.
- Set `a4c` to the macro average recall score of the this model.

**Note:** Macro average takes the mean of each class’s precision/recall without considering how many samples each class has, which is appropriate for a balanced evaluation.

In [42]:
 # Your answer here

a4a = bal_acc                  # replace 0 with your answer, use variable or expression from above

In [43]:
# DO NOT change this cell in any way

print(f'a4a = {a4a:.4f}')

a4a = 0.8429

In [44]:
 # Your answer here

a4b = macro_precision                     # replace 0 with your answer, may copy from the displayed results

In [45]:
# DO NOT change this cell in any way

print(f'a4b = {a4b:.4f}')

a4b = 0.7765

In [46]:
 # Your answer here

a4c = macro_recall                    # replace 0 with your answer, may copy from the displayed results

In [47]:
# DO NOT change this cell in any way

print(f'a4c = {a4c:.4f}')

a4c = 0.8429

## Problem 5: Understanding Precision, Recall, F1, and Balanced Accuracy

**Tutorial**

In binary classification, you will often evaluate these key metrics:

* **Precision**: *Of all the positive predictions the model made, how many were actually correct?*

  * High precision = few false positives
  * Low precision = many false positives

* **Recall**: *Of all the actual positive cases, how many did the model correctly identify?*

  * High recall = few false negatives
  * Low recall = many false negatives

* **F1 score**: The harmonic mean of precision and recall, which balances them in a single measure.

  * F1 is **highest** when precision and recall are both high and similar in value.
  * If precision and recall are unbalanced, F1 will drop to reflect that imbalance.

* **Balanced accuracy**: The average of recall across both classes (positive and negative).

  * It ensures the classifier is performing reasonably well on *both* groups, correcting for class imbalance.
  * Balanced accuracy is especially important if the classes are very unequal in size.

**Typical trade-offs to remember:**

* **Higher recall, lower precision**: the model finds most true positives but also mislabels some negatives as positives
* **Higher precision, lower recall**: the model is strict about positive predictions, but misses some true positives
* **Balanced precision and recall (good F1)**: a practical compromise
* **Balanced accuracy**: checks fairness across both classes

###  Problem 5 Graded Question (multiple choice)

A bank uses your model to identify customers earning over $50K for a premium product invitation. Based on your final test set evaluation, including macro-averaged precision and recall, which of the following best describes what might happen?

(1) The bank will miss some eligible high-income customers, but will avoid marketing mistakes by sending invitations only to those it is  confident about.

(2) The bank will successfully reach most high-income customers, but will also waste resources sending invitations to some low-income customers.

(3) The bank will perfectly identify all high-income and low-income customers, resulting in no wasted invitations and no missed opportunities.

In [48]:
 # Your answer here

a5 = 1                    # replace 0 with one of 1, 2, or 3

In [49]:
# DO NOT change this cell in any way

print(f'a5 = {a5}')

a5 = 1

### Appendix One: Feature Engineering

Here are some practical feature-engineering tweaks worth considering (beyond simply ordinal-encoding the categoricals)

| Feature(s)                                                           | Why the tweak can help                                                                                                                                                     | How to do it (quick version)                                                                                                                                                    | Keep / drop?      |
| -------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------- |
| **`fnlwgt`**                                                         | Survey sampling weight, not a predictor. Leaving it in often lets the model “cheat.”                                                                                       | `df = df.drop(columns=["fnlwgt"])`                                                                                                                                              | **Drop**          |
| **`education` *vs.* `education-num`**                                | They encode the **same** information twice (categorical label and its ordinal rank). Keeping both is redundant and can cause leakage of a perfectly predictive feature.    | Usually keep **only one**. For tree models `education-num` is simplest: `df = df.drop(columns=["education"])`                                                                   | **Drop one**      |
| **`capital-gain`, `capital-loss`**                                   | Highly skewed; most values are zero with a long upper tail. The sign (gain vs. loss) matters, but treating them separately wastes a feature slot.                          | 1) Combine: `df["capital_net"] = df["capital-gain"] - df["capital-loss"]`; 2) Log-transform to reduce skew: `df["capital_net_log"] = np.log1p(df["capital_net"].clip(lower=0))` | Replace originals |
| **`age`, `hours-per-week`**                                          | Continuous but with natural plateaus—trees handle splits fine, yet log or square-root scaling can soften extreme values; bucketing makes partial-dependence plots clearer. | Simple bucket: `df["age_bin"] = pd.cut(df["age"], bins=[16,25,35,45,55,65,90])` (optional)                                                                                      | Optional          |
| **Missing categories** (`workclass`, `occupation`, `native-country`) | HGB handles `-1`/`-2` codes fine, but you may want *explicit* “Missing” bucket for interpretability.                                                                       | Use `encoded_missing_value=-2` during encoding.                                                                                                            | Keep as is        |
| **Rare categories in `native-country`**                              | Hundreds of low-frequency countries dilute signal; grouping boosts stability.                                                                                              | Map infrequent categories to “Other”:                                                                                                                                           |                   |


#### Minimum set of tweaks (good baseline, low effort)

1. **Drop `fnlwgt`.**  
2. **Keep `education-num`, drop `education`.**  
3. **Combine `capital-gain` and `capital-loss` into `capital_net`** (optionally add a log-scaled version).  
4. Leave other numeric/categorical features as is; your histogram-GBDT will cope.